---
title: "Depuracion"
author: "SalomeAristizabal"
date: "27/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


##Cargando la base de datos

```{r}
load("datos.RData")
```


```{r}
colnames(Base_final)
```


```{r}
nombres <- c(
  "Genero","Edad","Estado_civil","Lugar_nacimiento","Vive_hogar_padre","Educacion_padre","Vive_hogar_madre","Educacion_madre","Etnia","Num_Subsidios","Cant_hogares_vivienda","Tipo_vivienda","Material_pisos","Energia_electrica","Estrato","Acueducto","Alcantarillado","Basuras_semana","Nivel_educativo","Estudia","Afiliado","Salud_general","Uso_celular","Num_cuartos","Gas_natural","Telefonia_fija","Ingresos_hogar","Contrato_vivienda","Ultimo_pago_energia","Pago_mes_energia","Num_integrantes","Num_hijos"
)
```

```{r}
colnames(Base_final) <- nombres
```

```{r}
#rm(nombres)
```

```{r}
str(Base_final)
```



```{r}
sapply(1:32, function(i){
  boxplot(Base_final$Num_hijos~Base_final[, i], xlab = nombres[i])
})
```




* Variables significativas según el boxplot:

- Genero
- Edad
- Estado_civil
- Educacion_madre
- Num_Subsidios
- Cant_hogares_vivienda
- Tipo_vivienda
- Estrato
- Num_cuartos
- Num_integrantes


```{r}
par(mfrow=c(2,2))
plot(Base_final$Num_hijos~ Base_final$Edad)
plot(Base_final$Num_hijos~ Base_final$Ingresos_hogar)
plot(Base_final$Num_hijos~ Base_final$Ultimo_pago_energia)
plot(Base_final$Num_hijos~ Base_final$Pago_mes_energia)
```

```{r}
# Variables interesantes

c(
  "Genero",
  "Num_integrantes",
  "Num_cuartos",
  "Estrato",
  "Material_pisos",
  "Tipo_vivienda",
  "Num_Subsidios",
  "Educacion_madre",
  "Estado_civil",
  "Ultimo_pago_energia",
  "Ingresos_hogar",
  "Contrato_vivienda"
)
```


```{r}
barplot(table(Base_final$Num_hijos))
```


```{r}
plot(Base_final$Ingresos_hogar,Base_final$Edad, xlim = c(0,60000000), col = Base_final$Num_hijos, pch=19)
```


```{r}
library(ggplot2)

ggplot(Base_final) +
 aes(x = Nivel_educativo, y = Num_hijos, fill = Genero) +
 geom_boxplot() +
 scale_fill_hue() +
 theme_minimal() +
 facet_grid(vars(Genero), vars())
```


```{r}
colors()[1:14]
```


```{r}

Base_final <- Base_final %>% 
  mutate(
    Genero = factor(Genero)
  )


mod1 <- lm(Num_hijos~., data = Base_final)





summary(mod1)
```

## Juanes


Seleccionemos las variables mas relevantes para explicar a y.

Transformando las varibles en factores

```{r}

for (i in 1:length(names(Base_final))) {
  if(is.integer(Base_final[,i])){
    Base_final[ ,i] <- as.factor(Base_final[ ,i])
  }
  
}

str(Base_final)

Base_final <- na.omit(Base_final) # quitamos los NA's de nuestra base de datos
```

Veamos con Lasso regresion.

```{r}
require(glmnet)
x <- model.matrix(Num_hijos ~ ., Base_final)[,-1]
y <- Base_final$Num_hijos

gridz <- 10^seq(-2,10, length = 100)
lasso.mod <- glmnet(x, y, alpha = 1, lambda = gridz)
```

```{r}
require(plotmo)
plot_glmnet(lasso.mod, xvar = 'lambda', grid.col="lightgray", label = 31, xlim = c(-5, 0))
```




















